#2708 #2556
hydroshare/hydroshare pull request #3370
Opened 2019-05-01 19:37 UTC by mraocuahsi

Fixes #2708. #2556

2019-05-01 19:43 UTC, cuahsimarko commented
@sblack-usu @pkdash could one of you please review this?

2019-05-01 21:22 UTC, pkdash requested changes

2019-05-01 21:22 UTC, pkdash commented on hs_core/page_processors.py
>  """Page processors for hs_core app."""
Why are we reversing these changes that I had made in cleaning up the page_preprocessor?

2019-05-01 21:51 UTC, sblack-usu commented on hs_core/templates/403.html
> +<meta http-equiv="REFRESH" content="0;url=http://localhost:8000/accounts/login">
localhost?  I think there are a lot of things in this branch that were meant to be here.

2019-05-06 13:50 UTC, cuahsimarko commented
Closing will address with everyone. I'm sitting with Mahesh right now.

2019-05-06 13:50 UTC, closed without merging