4472 4473 last updated fix
hydroshare/hydroshare pull request #4487
Opened 2022-02-11 21:30 UTC by hyi

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

2022-02-11 21:33 UTC, hyi commented
This PR will fix both issues #4472 and #4473, so last updated time stamp for resources affected by resource versioning fix will be set back it their old time stamp and the replaced resources will maintain their time stamp rather than replaced with their versioned resources' time stamps. @pkdash I assigned you as a reviewer.

2022-02-11 22:07 UTC, hydrocheck commented
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4487](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4487)

2022-02-14 18:29 UTC, pkdash requested changes

2022-02-14 18:29 UTC, pkdash commented on hs_core/management/commands/fix_resource_versioning_date.py
> +                res.updated = res_date
I think we also need to update the `Date` metadata for date type `modified`.

2022-02-14 23:40 UTC, hyi commented
@pkdash I have addressed all of your comments. See if they look good now. Thanks!

2022-02-15 14:26 UTC, pkdash requested changes
Left a minor change suggestion.

2022-02-15 14:26 UTC, pkdash commented on hs_core/management/commands/fix_resource_versioning_date.py
> +from hs_core.models import Date
Not needed

2022-02-15 14:48 UTC, pkdash approved these changes

2022-02-15 17:40 UTC, merged