async delete files [#4065]
hydroshare/hydroshare pull request #4615
Opened 2022-05-10 20:41 UTC by devincowan

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

2022-05-10 21:18 UTC, hydrocheck commented
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4615](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4615)

2022-05-13 18:47 UTC, devincowan commented
@Maurier I didn't see a good way to speed up file deletion. But at least we can provide UI feedback and do it async without page reload. LMK if I missed an obvious way to speed things up...thanks

2022-05-13 18:47 UTC, devincowan commented
@Maurier I didn't see a good way to speed up file deletion. But at least we can provide UI feedback and do it async without page reload. LMK if I missed an obvious way to speed things up...thanks

2022-05-13 19:05 UTC, Maurier requested changes
Looks good. Left a minor suggestion to improve UX.

2022-05-13 19:08 UTC, Maurier commented
> @Maurier I didn't see a good way to speed up file deletion. But at least we can provide UI feedback and do it async without page reload. LMK if I missed an obvious way to speed things up...thanks

The frontend already sends all the file ids to delete in one request to the backend. So, any improvement that could be done has to look into the backend implementation of files deletion. But I think the work done in this PR effectively covers the scope outlined here.

2022-05-13 19:10 UTC, devincowan commented on theme/static/css/hydroshare_core.css
> +#fb-files-container li.deleting {
@Maurier thanks! I actually had `pointer-events: none;` in there but reverted it when I added the `deleteList.css("cursor", "wait")` but you're right, the **wait** doesn't stop events from propagating in our FB, so good call, thank you!

2022-05-13 19:10 UTC, Maurier approved these changes
Looks good

2022-05-13 19:17 UTC, devincowan commented
sorry @Maurier I found one more small improvement after your approval :( [634e158](https://github.com/hydroshare/hydroshare/pull/4615/commits/634e1589db3af37869c77fbaa3c424a8cfa29801)

2022-05-13 19:36 UTC, Maurier approved these changes

2022-05-13 23:18 UTC, merged