[#4648] add 'similar to'
hydroshare/hydroshare pull request #4678
Opened 2022-06-20 15:05 UTC by devincowan

resolves #4648 

### Pull Request Checklist: 
- [x] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [x] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. Create a resource
2. Click "related resources"
3. "Type of relationship" = "The content of this resource is similar to"
4. Add a citation. "Save Changes"
5. Save a bag of the resource and verify that the relationship is exported in the metadata XML
6. (alternatively) set DEBUG = False in settings.py and check the schemaorg script on the resource landing page: you will see the relation added in the "Citation" section

![image](https://user-images.githubusercontent.com/17934193/174892259-27520474-bbbf-408d-a104-417d2c3c0a30.png)

### needs the following for simultaneous deployment:
https://github.com/hydroshare/hsmodels/pull/34

2022-06-20 16:06 UTC, hydrocheck commented
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4678](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4678)

2022-06-27 13:26 UTC, pkdash requested changes

2022-06-27 15:26 UTC, devincowan commented on hs_core/models.py
>      # these are hydroshare custom terms that are not Dublin Core terms
Thank you Pabitra, great catch!

2022-06-27 18:41 UTC, pkdash approved these changes

2022-06-27 18:42 UTC, merged