4830 use jsonld to map geoconnex names
hydroshare/hydroshare pull request #4840
Opened 2022-11-15 18:59 UTC by devincowan

Resolves #4830 

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

2022-11-15 19:02 UTC, devincowan commented on theme/templates/resource-landing-page/geoconnex.html
> +    <script src="https://unpkg.com/jsonld@8.1.0/dist/jsonld.min.js"></script>
adds jsonld package so that we can "compact"

2022-11-15 19:05 UTC, devincowan commented on theme/static/js/hs-vue/geoconnex.js
> -      featureNameFieldMap: {
removed this static mapping

2022-11-15 19:06 UTC, hydrocheck commented
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4840](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-4840)

2022-11-15 19:07 UTC, devincowan commented on theme/static/js/hs-vue/geoconnex.js
>        },
remove this static mapping

2022-11-28 16:13 UTC, Maurier requested changes
Looks good. A few minor suggestions.

2022-11-28 16:13 UTC, Maurier commented on theme/static/js/hs-vue/geoconnex.js
> +    async getFeatureName(feature) {
I think this function `getFeatureName` is not called anywhere.

2022-11-28 16:13 UTC, Maurier commented on theme/static/js/hs-vue/geoconnex.js
> +      let array = featureJsonLd["@context"];
This array can be declared as a constant as well. And a better name could be used.

2022-11-28 16:13 UTC, Maurier commented on theme/static/js/hs-vue/geoconnex.js
> +          geoconnexApp.ignoredFeatures[collection.id].includes(feature.id)
This conditional can be simplified in one line as such: `geoconnexApp.ignoredFeatures[collection.id]?.includes(feature.id)`

2022-11-28 19:17 UTC, Maurier approved these changes

2022-11-28 21:13 UTC, merged