4801 geoconnex names
hydroshare/hydroshare pull request #5005
Opened 2023-03-09 16:46 UTC by devincowan

### Pull Request Checklist: 
- [ ] Positive Test Case Written by Dev

- [ ] Automated Testing

- [ ] Sufficient User and Developer Documentation

- [ ] Passing Jenkins Build

- [ ] Peer Code review and approval

### Positive Test Case
1. [Enter positive test case here]

2023-03-09 17:06 UTC, hydrocheck commented
| METRIC | VALUE |
|:-----:|:-----:|

[https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5005](https://sonarqube.cuahsi-workstation.com:9000/dashboard?id=hydroshare-5005)

2023-03-13 15:23 UTC, Maurier requested changes
@devincowan The UX feels great now and the code is also very well organized. 

A few minor errors that we can improve:

On page load:
![image](https://user-images.githubusercontent.com/2448568/224746050-5b09a031-6cc3-4824-9e53-01671a9f05b5.png)

After clearing the Collection select while it's loading:
![image](https://user-images.githubusercontent.com/2448568/224746543-5c0e1bef-6d66-45e7-80f2-b25036f70b07.png)

These probably can be avoided by adding some conditionals to check for `undefined`.

2023-03-13 17:12 UTC, devincowan commented
thanks @Maurier I hadn't seen these errors in Firefox. Was able to reproduce the 2nd one ("reading addLayer") in Chrome and fixed it in https://github.com/hydroshare/hydroshare/pull/5005/commits/0eb15a6c0e2ae4061a6bff8f98e327c744a55fe4

I haven't been able to reproduce the other error (on page load) even in Chrome.

2023-03-13 17:51 UTC, Maurier commented
@devincowan I think this error can be prevented rather than caught by changing occurrences of `geoconnexApp.searchLayerGroupDictionary[geojson.collection].addLayer` to `geoconnexApp.searchLayerGroupDictionary[geojson.collection]?.addLayer`

2023-03-13 18:26 UTC, devincowan commented
@Maurier thanks youre right that it can be prevented with the `?.` notation, but there will always be one extra layer that gets mapped after abort (leaving a "hanging" layer on the map). So I pushed [232efd5](https://github.com/hydroshare/hydroshare/pull/5005/commits/232efd5f17706bf4a09885a1cae77fb51761f248) to prevent the error rather than catching (as you suggest) while also avoiding the "one hanging layer" effect...

2023-03-13 18:54 UTC, Maurier commented on theme/static/js/hs-vue/geoconnex.js
> +      // await new Promise((resolve)=>{
@devincowan Minor code cleanup to do here.

2023-03-13 19:00 UTC, Maurier approved these changes
Looks good

2023-03-14 00:01 UTC, merged